project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('animeval.urls')),
]+ static(settings.STATIC_URL, document_root = settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

animeval/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.core.mail import send_mail
from django.contrib.auth.base_user import BaseUserManager
from django_mysql.models import ListCharField, ListTextField

# Create your models here.

class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, username, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        if not username:
            raise ValueError('The given username must be set')
        email = self.normalize_email(email)
        username = self.model.normalize_username(username)
        user = self.model(username=username, email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(username, email, password, **extra_fields)

    def create_superuser(self, username, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(username, email, password, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):
    """
    An abstract base class implementing a fully featured User model with
    admin-compliant permissions.
    Username and password are required. Other fields are optional.
    """
    username_validator = UnicodeUsernameValidator()

    username = models.CharField(
        _('username'),
        max_length=150,
        unique=True,
        help_text=_('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[username_validator],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)
    email = models.EmailField(_('email address'), blank=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')
        #abstract = True # ここを削除しないといけないことを忘れない！！！！！！！！！！

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

class ProfileModel(models.Model):

    GENDER_CHOICES = (
        (1,'男性'),
        (2,'女性'),
        (3,'その他'),
    )

    user = models.ForeignKey(User, on_delete = models.CASCADE,related_name = 'user')
    nickname = models.CharField(max_length = 10,verbose_name = 'ニックネーム')
    gender = models.IntegerField(choices = GENDER_CHOICES, blank = True)
    favarite_anime = models.CharField(max_length = 100)
    avator = models.ImageField(upload_to = 'images/', blank = True)
    

    def __str__(self):
        return self.nickname

class AnimeModel(models.Model):
    title = models.CharField(max_length = 100)
    started = models.CharField(max_length = 10,default = 'None')
    genre = models.CharField(max_length = 15, default= 'None')
    corporation = models.CharField (max_length = 100,default = 'None')
    character_voice = ListCharField(
        base_field = models.CharField(max_length = 20),
        size = 6,
        max_length = (6 * 21),
        default = ['None']
    )

    def __str__(self):
        return self.title

class ReviewModel(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    profile = models.ForeignKey(ProfileModel, on_delete = models.CASCADE)
    anime = models.ForeignKey(AnimeModel, on_delete = models.CASCADE)
    review_title = models.CharField(max_length =50)
    review_content = models.TextField()
    evaluation = ListTextField(
        base_field = models.IntegerField(),
        size = 5,
        default = [0,0,0,0,0]
    )
    evaluation_ave = models.DecimalField(max_digits=2, decimal_places=1)
    post_date = models.DateTimeField(auto_now_add = True)

class Counter(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    counter = ListTextField(
        base_field = models.IntegerField(),
        size = 8,
        default = [0,0,0,0,0,0,0,0]
    )

class AccessReview(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    review = models.ForeignKey(ReviewModel, on_delete = models.CASCADE)

    def __str__(self):
        return 'アクセス名:{} / レビュータイトル:{}'.format(self.user.username, self.review.review_title)

class Comment(models.Model):
    comment = models.CharField(max_length = 255)
    review = models.ForeignKey(ReviewModel, on_delete = models.CASCADE)
    user = models.ForeignKey(User,on_delete = models.CASCADE)
    created_at = models.DateTimeField(auto_now_add = True)

class ReplyComment(models.Model):
    reply = models.CharField(max_length = 255)
    comment = models.ForeignKey(Comment, on_delete = models.CASCADE)
    user = models.ForeignKey(User,on_delete = models.CASCADE)
    created_at = models.DateTimeField(auto_now_add = True)

class Like(models.Model):
    review = models.ForeignKey(ReviewModel, on_delete = models.CASCADE)
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    like = models.IntegerField(default = 0)
    created_at = models.DateTimeField(auto_now_add = True)

templates/base.html
{% load static%}
<!doctype html>
<html lang="ja">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://kit.fontawesome.com/3002737d6d.js" crossorigin="anonymous"></script>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
          integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/css/all.css' %}">
    <title>AnimEval</title>
  </head>
<body>
  
  <!-- ナビバー -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">AnimEval</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      {% if user.is_authenticated %}
      <a class = 'nav-items' href = "{% url 'home' %}" id = 'home'>Home</a>
      <a href = "#" class = 'nav-items' >search</a>
      <a href="{% url 'profile' profile.id %}" class = 'nav-items' id = 'mypage'>mypage</a>
      <a href="{% url 'logout' %}" class = 'nav-items' id = 'logout'>logout</a>
      <a href="{% url 'create_review' %}" class = 'nav-items' id = 'post'>投稿</a>
        <div class="d-flex justify-content-center">
          <form method="GET" action="#" class = search_container>
            <input type="text" name="q" placeholder = 'キーワードを検索' value="{{request.GET.q}}" size = '25'>
            <i class="fas fa-search"></i>
            <button type="submit"></button>
          </form>
        </div>
        <a class="nav-item nav-link text-dark" href="{% url 'profile' profile.id %}"></a>
      </div>
          {% if query %}
          <p class="text-center font-weight-bold h4">{{object_list.count}}件</p>
          {% endif%}

          {% else %}          
          <a class="nav-item nav-link text-dark" href="#">
            ログインはこちらから
          </a>
          <a class="nav-item nav-link text-dark" href="#">
            会員登録はこちらから
          </a>
          {% endif %}
        </ul>
      </div>
    </nav>
    <!-- メインコンテント -->
    <div class="container mt-3">
      {% block content %}{% endblock %}
    </div>
    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
            integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
    integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
    crossorigin="anonymous"></script>
  </body>
  </html>

templates/base2.html
{% load static%}
<!doctype html>
<html lang="ja">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
    integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/css/all.css' %}">

    <title>AnimEval</title>
</head>
<body>
    <!-- メインコンテント -->
    <div class="container mt-3">
        {% block content %}{% endblock %}
    </div>  
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
            integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
            integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
            crossorigin="anonymous"></script>
</body>
</html>

templates/create_review.html
{% extends 'base.html' %}
{% load static %} 
{%block content%}
    <link rel="stylesheet" href="{% static '/css/post.css' %}">
    <div id = 'wrapper'>
        <div id = 'review'>
            <section id = 'title'>
                <h4>{{context}}</h4>
                <h4>レビューを書いてみよう</h4>
            </section> 
            
            <section id = 'item'>
                <form action="" method = 'POST'>{% csrf_token %}
                    <div>
                        <p>アニメタイトル</p>
                        <input type="text" name = 'anime' id = 'anime-title' onkeyup ='inputCheck();' placeholder="正式名称でお願いします">
                        <ul id = 'search'></ul>
                    </div>
                    <div id = 'spoiler-question'>
                        <p>ネタバレを含みますか？</p>
                        <p>
                            No<input type="radio" value = '0' name = 'spoiler' checked = 'checked'>
                            Yes<input type="radio" value = '1' name = 'spoiler'>
                        </p>
                    </div>
                    <div id = 'review-content'>
                        <p>レビュー(1行目はタイトルを記入してください)</p>
                        <textarea name="review" id="" cols="50" rows="10"></textarea>
                    </div>
                    <div id = 'evaluation-title'>
                        <p>各項目の評価</p>
                    </div>
                    <div id='evaluation'>
                        <div>
                        <p>ストーリー</p>
                            <select name="eva_senario">
                                <option value=1>1</option>
                                <option value=2>2</option>
                                <option value=3>3</option>
                                <option value=4>4</option>
                                <option value=5>5</option>
                            </select>
                        </div>
                        <div>
                        <p>作画</p>
                            <select name="eva_drawing">
                                <option value=1>1</option>
                                <option value=2>2</option>
                                <option value=3>3</option>
                                <option value=4>4</option>
                                <option value=5>5</option>
                            </select>
                        </div>
                        <div>
                        <p>音楽</p>
                            <select name="eva_music">
                                <option value=1>1</option>
                                <option value=2>2</option>
                                <option value=3>3</option>
                                <option value=4>4</option>
                                <option value=5>5</option>
                            </select>
                        </div>
                        <div>
                        <p>キャラクター</p>
                            <select name="eva_character">
                                <option value=1>1</option>
                                <option value=2>2</option>
                                <option value=3>3</option>
                                <option value=4>4</option>
                                <option value=5>5</option>
                            </select>
                        </div>
                        <div>
                        <p>声優</p>
                            <select name="eva_cv">
                                <option value=1>1</option>
                                <option value=2>2</option>
                                <option value=3>3</option>
                                <option value=4>4</option>
                                <option value=5>5</option>
                            </select>
                        </div>
                    </div>
                    <div id = 'button'>
                        <input type="submit" value = '登録' name = 'post'>
                    </div>
                </form>
            </section>
        </div>
    </div>
    
    <script>
        const list = [
            {% for anime in anime_title_list %}
            "{{anime}}",
            {% endfor %}
        ];
        
        function inputCheck(){
            render();
            const nameList = []
            let elInput = document.getElementById('anime-title').value;
            let elIn = document.getElementById('search');
            list.forEach( (item) => {
                if (elInput !== ''){
                    if (item.indexOf(elInput) !== -1) {
                        nameList.push(item);
                    }
                }
            });
            nameList.forEach((item) => {
                const newEl = document.createElement('li');
                let newCtx = document.createTextNode(item);
                newEl.appendChild(newCtx);
                newEl.setAttribute('class','anime-list');
                elIn.appendChild(newEl);
            })
            clickEvent();
        }

        let render = () => {
            const animeList = document.getElementById('search');
            animeList.innerHTML = '';
        }    

        let clickEvent = () => {
            document.getElementById('search').addEventListener('click', (e) => {
                console.log(e.target);
                document.getElementById('anime-title').value = e.target.textContent;
                render();
            })
        }
        </script>
{%endblock content%}

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static '/css/all.css' %}">
<link rel="stylesheet" href="{% static '/css/home.css' %}">
<div id = 'wrapper'>
    {% if rec_anime%}
    <section id = 'trend'>
        <div id = 'trend-anime'>
            <div id = 'trend-title' class = 'link-title'>
                <h4>あなたへのおすすめアニメ : {{rec_anime.title}}</h4>
            </div>
            <div id = 'trend-info'>
                <div id = 'trend-graph'>
                    <p class = 'trend-info-title'>あなたへのおすすめ度</p>
                    <img src="{% url 'trend_image' rec_anime.pk %}" alt="" width = '300' height = '200'>
                </div>
                <div id = 'trend-detail'>
                    <p class = 'trend-info-title'>アニメ情報</p>
                    <ul id = 'trend-detail1'>
                        <li>
                            <h6>総合順位 : {{rank}} 位</h6>
                        </li>
                        <li>
                            <h6>ジャンル内順位 : {{rank}} 位</h6>
                        </li>
                        <li>
                            <h6>投稿数 : {{review_count}} 件</h6>
                        </li>
                        <li>
                            <h6>ジャンル : {{rec_anime.genre}}</h6>
                        </li>
                    </ul>
                </div>
                <div id = 'reviwer-list'>
                    <p class = 'trend-info-title'>評価しているユーザー</p>
                    <ul id = 'reviwer-list-info'>
                        {% for review in rec_anime_reviews %}
                        <li>
                            <div id = profile-info>
                                <div>
                                    <img src="{{review.profile.avator.url}}" alt="" width = 70 height = 70 id = 'avator'>
                                    <p>{{review.profile.nickname}}</p>
                                </div>
                                <div>
                                    <h6><a href="{% url 'review_detail' review.pk %}">{{review.evaluation_ave}} {{review.review_title}}</a></h6>
                                </div>
                            </div>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </section>
    {% endif %}
    <section id = contents>
        <div id = 'review-list'>
            <h6 class = 'link-title'>レビュー一覧</h6>
            {% for review in review_list %}
            <div id = 'review-item'>
                <div id = 'profile'>
                    <img src="{{review.profile.avator.url}}" alt="" width = 100 height = 100 id = 'avator'>
                    <p>{{review.profile.nickname}}</p>
                </div>
                <div id = 'review'>
                    <div id = 'title'>
                        <a href="{% url 'review_detail' review.pk %}">
                        <div id = 'review-title'>
                            <h4>{{review.evaluation_ave}}</h4>
                            <h4>{{review.review_title}}</h4>
                        </div>
                        </a>
                        <div id = 'anime-title'>
                            <h6>Anime : {{review.anime.title}}</h6>
                            <h6>Genre : {{review.anime.genre}}</h6>
                        </div>
                    </div>
                    <div id = 'review-content'>
                        <p id = 'content'>{{review.review_content | linebreaksbr}}</p>
                        <p id = 'detail-btn'>続きを見る</p>
                    </div>
                    <div id = 'icon'>
                        <p>Comment <i class="fas fa-comments"></i> ({{review.comment_set.count}})</p> 
                        <a id = 'like' href="{% url 'like' review.pk request.user.pk %}">イイね<i class="fas fa-thumbs-up"></i></a>
                            ({{review.like_set.count}})
                        </p>
                        <p>{{review.post_date}}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <div id = 'link-list'>
            <div id = 'anime-list' class = 'link'>
                <p class = 'link-title'>アニメ一覧</p>
                <ul>
                    {% for anime in all_anime_list %}
                        <li>{{anime.title}}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </section>
</div>
<script src = "{% static '/javascript/home.js' %}"></script>
{% endblock content %}

templates/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static '/css/profile.css' %}">

<div id = 'profile'>
    <section id = 'section1'>

        <div id = 'top'>
            <h4>{{profile.nickname}}</h4>
            <img src="{{profile.avator.url}}" alt="profile image" width = 100 height = 100 id = 'avator'>
        </div>

        <div id = 'data'>
            <ul id = 'count'>
                <li>
                    <p>{{profile.get_gender_display}}</p>
                    <label for = 'name'>gender</label>
                </li>
                <li>
                    <p>{{review_num}}件</p>
                    <label for = 'name'>投稿数</label>
                </li>
            </ul>
            <div id = 'update'>
                <h6>プロフィールを編集</h6>
            </div>
        </div>

    </section>

    <section id = 'section2'>

        <div id = 'list'>
            <div id = 'title'>
                <h6 id = 'title_post'>投稿一覧</h6>
                <form method="GET" action="#" class = search_container id = 'search_box'>
                    <input type="text" name="q" placeholder = 'キーワードを検索' value="{{request.GET.q}}" size = '25'>
                    <i class="fas fa-search"></i>
                    <button type="submit"></button>
                </form>
            </div>
            <div id = 'review-list'>
                {% for review in review_list %}
                    <div id = 'review'>
                        <div id = 'title1'>
                            <div id = 'review-title'>
                                <h4>{{review.evaluation_value_ave}}</h4>
                                <h4>{{review.review_title}}</h4>
                            </div>
                            <div id = 'anime-title'>
                                <h6>Anime : {{review.anime_title.anime_title}}</h6>
                            </div>
                        </div>
                            <div id = 'review-content'>
                                <p id = 'content'>{{review.review_content | linebreaksbr}}</p>
                            </div>
                        <div id = 'icon'>
                            <p>{{review.nickname.nickname}}</p>
                            <p>{{review.post_date}}</p>
                            <p>Comment</p>
                            <p>いいね</p>
                        </div>
                        <div id = 'update-delete'>
                            <a href="{% url 'update_review' review.pk %}">編集する</a>
                            <a href="{% url 'delete_review' review.pk %}">削除する</a>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div id = 'context'>
                <h2>{{ context }}</h2>
            </div>
        </div>

    </section>
</div>
<script src = "{% static '/javascript/profile.js' %}"></script>
{% endblock content %}

templates/review_detail.html
{% extends 'base.html' %}
{% load static %} 
{% block content %}
    <link rel="stylesheet" href="{% static '/css/all.css' %}">
    <link rel="stylesheet" href="{% static '/css/detail.css' %}">

<div id = 'wrapper'>
    <div id = 'main'>
        <div id = 'review'>
            <section id = 'section1'>
                <div id = 'review-header'>
                    <div id = 'profile'>
                        <img src="{{profile.avator.url}}" alt="profile image" width = 100 height = 100 id = 'avator'>
                        <p>{{review.profile.nickname}}</p>
                    </div>
                    <div id = 'title'>
                        <div id = 'review-title'>
                            <h4>{{review.review_title}}</h4>
                        </div>
                        <div id = 'anime-title'>
                            <p>{{review.anime.title}} (ジャンル : {{review.anime.genre}})</p>
                        </div>
                    </div>
                </div>
                <div id = 'review-content'>
                    <p>{{review.review_content}}</p>
                </div>
            </section>
            <section id = 'section2'>
                <div id = 'evaluation-detail'>
                    <p>総合評価 : {{review.evaluation_ave}}</p>
                </div>
                <div id = 'evaluation-graph'>
                    <img src= "{% url 'image' review.pk %}" width = '400' height = '300'>
                </div>
            </section>
        </div>
        <div id = 'comment-list'>
            <p>コメント一覧</p>
            {% for comment in comment_list %}
                <div id = 'comment-header'>
                    <p>{{comment.user.username}}</p> 
                    <p id = 'comment-date'>{{comment.created_at}}</p>
                </div>
                <div id = 'comment-content'>
                    <p id = 'content'>{{comment.comment}}</p>
                    <a href=""><p>続きを読む</p></a>
                </div>
                <div id = 'reply'>
                    <a href="{% url 'create_reply' comment.pk %}"><p>返信</p></a>
                </div>
                <div>
                    <a href="" id = 'reply-display'>返信を表示する</a>
                    <div id = 'reply-list' style = 'display:none'>
                        {% for reply in reply_list %}
                            {% if reply.comment == comment %}
                            <div id = 'reply-header'>
                                <p>{{reply.user.username}}</p>
                                <p id = 'reply-date'>{{reply.created_at}}</p>
                            </div>
                            <div id = 'reply-content'>
                                <p id = 'content'>{{reply.reply}}</p>
                                <a href=""><p>続きを読む</p></a>
                            </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
            <a href="{% url 'create_comment' review.pk %}">コメントを書く</a>
        </div>
    </div>    
    
    <div>
        <section id = 'section3'>
            <div id = 'random-review-header'>
                <h4>{{review.profile.nickname}}さんのその他の投稿</h4>
            </div>
            <div id = 'random-review-list'>
                {% for review in review_list%}
                    <div id = 'random-review'>
                        <div id = 'random-review-title'>
                            <h6>{{review.evaluation_value_ave}} {{review.review_title}}</h6>
                            <p>Anime : {{review.anime_title.anime_title}}</p>
                        </div>
                        <div id = 'random-review-content'>
                            <p id = 'content'>{{review.review_content}}</p>
                            <a href="{% url 'review_detail' review.pk %}"><p>続きを見る</p></a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </section>
    </div>
</div>
<script src = "{% static '/javascript/detail.js' %}"></script>

{% endblock content %}